



workflows:
  build_pojavlauncher_ios:
    name: Build PojavLauncher iOS
    environment:
      vars:
        JAVA_VERSION: "21"
    scripts:
      - name: Inject Java runtime and control layout
        script: |
          echo "Using Java version $JAVA_VERSION"
          mkdir -p $CM_BUILD_DIR/resources/java$JAVA_VERSION
          cp -R resources/java$JAVA_VERSION/* $CM_BUILD_DIR/PojavLauncher/app/src/main/java
          cp layout/pe_controls.json $CM_BUILD_DIR/PojavLauncher/app/src/main/assets/controls.json
      - name: Build with Xcode
        script: |
          xcodebuild -workspace PojavLauncher.xcworkspace -scheme PojavLauncher -configuration Release build
    artifacts:
      - build/PojavLauncher.ipa
    ios_signing:
      distribution_type: ad-hoc
      bundle_identifier: net.kdt.pojavlaunch

