

workflows:
  launcher-build:
    name: Launcher Build
    working_directory: ./launcher
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ipa
    artifacts:
      - build/ios/ipa/*.ipa
