





distribution_type: development
bundle_identifier: net.kdt.pojavlaunch

ios:
  build_settings:
    method: development

scripts:
  - name: Inject Java runtime and control layout
    script: |
      echo "Injecting new version JAVA_VERSION and layout SCROLLS_LAYOUT"
      sed -i -e "s|OLD_JAVA_VERSION|NEW_JAVA_VERSION|g" $SOURCE_DIR/JavaVersion.java
      sed -i -e "s|OLD_SCROLLS_LAYOUT|NEW_SCROLLS_LAYOUT|g" $SOURCE_DIR/layouts/scrolls_layout.json

  - name: build with Xcode
    script: |
      cd ios && xcodebuild -workspace PojavLauncher.xcworkspace -scheme PojavLauncher -sdk iphoneos -configuration Release archive -archivePath $BUILD_DIR/PojavLauncher.xcarchive
      xcodebuild -exportArchive -archivePath $BUILD_DIR/PojavLauncher.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $BUILD_DIR/build
