


workflows:
  pojavlauncher-ios-build:
    name: Build PojavLauncher with Java 21
    environment:
      vars:
        JAVA_VERSION: "21"
        RUNTIME_PATH: "$CM_BUILD_DIR/java21"
    scripts:
      - name: Inject Java Runtime
        script: |
          mkdir -p $RUNTIME_PATH
          cp -R $CM_SOURCE_DIR/java21/* $RUNTIME_PATH/
          echo "Injected Java 21 to $RUNTIME_PATH"
      - name: Build App with Xcode
        script: |
          cd ios
          xcodebuild -workspace PojavLauncher.xcworkspace \
            -scheme PojavLauncher \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_IDENTITY="Apple Development" \
            PROVISIONING_PROFILE_SPECIFIER="pojavlaunch-profile"
    artifacts:
      - build/**/PojavLauncher.ipa
    export_options:
      method: development
