



distribution_type: development
bundle_identifier: net.kdt.pojavlaunch

environment:
  vars:
    JAVA_VERSION: "java-21-openjdk"
    SCROLLS_LAYOUT: "pe_controls.json"

ios:
  build_settings:
    method: development

scripts:
  - name: Configure runtime and controls
    script: |
      echo "Injecting Java version: ${JAVA_VERSION}"
      echo "Injecting control layout: ${SCROLLS_LAYOUT}"
      
      sed -i -e "s|OLD_JAVA_VERSION|${JAVA_VERSION}|g" $SOURCE_DIR/JavaVersion.java
      sed -i -e "s|OLD_SCROLLS_LAYOUT|${SCROLLS_LAYOUT}|g" $SOURCE_DIR/layouts/scrolls_layout.json

  - name: Build with Xcode
    script: |
      cd ios
      xcodebuild -workspace PojavLauncher.xcworkspace -scheme PojavLauncher -sdk iphoneos -configuration Release archive -archivePath $BUILD_DIR/PojavLauncher.xcarchive
      xcodebuild -exportArchive -archivePath $BUILD_DIR/PojavLauncher.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $BUILD_DIR/build
