

workflows:
  ios-build:
    name: Build PojavLauncher with Java 21
    environment:
      ios_signing:
        distribution_type: ad-hoc
        bundle_identifier: com.joxi39477.pojavlauncher
      vars:
        XCODE_PROJECT: "PojavLauncher.xcodeproj"
        XCODE_SCHEME: "PojavLauncher"
    scripts:
      - name: Pre-build – Inject Java & Controls
        script: |
          echo "Injecting Java 21 runtime and PE layout..."
          cp -R resources/java21/* $FCI_BUILD_DIR/PojavLauncher/assets/java21/
          cp layout/pe_controls.json $FCI_BUILD_DIR/PojavLauncher/assets/layout.json
      - name: Build IPA
        script: |
          xcodebuild -project $XCODE_PROJECT \
                     -scheme $XCODE_SCHEME \
                     -sdk iphoneos \
                     -configuration Release \
                     archive -archivePath build/PojavLauncher.xcarchive
          xcodebuild -exportArchive \
                     -archivePath build/PojavLauncher.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath build/IPA
    artifacts:
      - build/IPA/*.ipa



