

workflows:
  pojavlauncher-ios-build:
    name: Build PojavLauncher with Java 21
    environment:
      vars:
        JAVA_VERSION: "21"
        RUNTIME_PATH: "$CM_BUILD_DIR/java21"
      ios_signing:
        provisioning_profiles:
          - pojavlaunch-profile
        certificates:
          - pojavlaunch-cert
      xcode: latest
    scripts:
      - name: Set up Java 21 Runtime
        script: |
          mkdir -p $RUNTIME_PATH
          cp -R $CM_SOURCE_DIR/java21/* $RUNTIME_PATH/
      - name: Build App
        script: |
          xcodebuild -workspace PojavLauncher.xcworkspace \
            -scheme PojavLauncher \
            -configuration Release \
            CODE_SIGN_IDENTITY="Apple Development" \
            PROVISIONING_PROFILE_SPECIFIER="pojavlaunch-profile"
    artifacts:
      - build/**/PojavLauncher.ipa
    export_options:
      method: development
