





workflows:
  build:
    name: Build iOS from launcher folder
    working_directory: ./launcher
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build IPA
        script: |
          flutter build ipa
    artifacts:
      - "build/ios/ipa/*.ipa"
