
environment:
  JAVA_VERSION: "java-21-openjdk"
  RUNTIME_PATH: "/var/mobile/Containers/Data/Application/<app-id>/Documents/PojavLauncher/.pojav/runtime/java-21-openjdk"
  LANG: "en_US.UTF-8"
  LC_ALL: "en_US.UTF-8"

scripts:
  pre_build:
    - echo "🔧 Preparing runtime injection..."
    - mkdir -p $RUNTIME_PATH
    - cp -r ./java21_build/* $RUNTIME_PATH/
    - echo "✅ Java 21 runtime injected at $RUNTIME_PATH"
  post_build:
    - echo "🚀 Build completed. Validating runtime..."
    - ls $RUNTIME_PATH
    - echo "🏁 Ready for launch!"

ios:
  build_settings:
    method: development
    export_options:
      distribution_type: development
      compileBitcode: false
      signingStyle: automatic
      provisioningProfiles:
        com.yourcompany.PojavLauncher: "Your_Dev_Profile_Name"

launcher_config:
  launcher_distribution: custom
  runtime_override: true
  runtime_path: "${RUNTIME_PATH}"
  runtime_type: jdk
  validate_runtime: true
