


name: launcher
description: Custom Minecraft launcher for iOS
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.14
  http: ^0.13.6
  # Add any custom or GitHub packages you're using here
  # Example:
  # flutter_launcher_icons:
  #   git:
  #     url: https://github.com/fluttercommunity/flutter_launcher_icons
  #     path: flutter_launcher_icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: ^0.9.2
  # Add any dev tools if needed

flutter:
  uses-material-design: true
  assets:
    - assets/
  # Add any other assets or fonts here
